# Generated by Django 4.0.4 on 2022-05-30 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('fullName', models.CharField(max_length=300)),
                ('verified', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=2000)),
                ('balance', models.IntegerField(default=0)),
                ('uid', models.CharField(default=uuid.UUID('a0f76ff9-9c88-4014-8e25-366814af4fe9'), max_length=3000)),
                ('isUser', models.BooleanField(default=False)),
                ('isDeliveryGuy', models.BooleanField(default=False)),
                ('isSeller', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=3000)),
                ('productPrice', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('postedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
