# Generated by Django 4.0.4 on 2022-06-18 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_user_uid_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('45c91fdb-5c36-4d50-8858-c9bab03c08a9'), max_length=3000),
        ),
    ]
