# Generated by Django 4.0.4 on 2022-06-18 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('0621894f-0a5d-4019-aab8-046003123c50'), max_length=3000),
        ),
    ]
